version: 3.x
services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./scripts/sql:/docker-entrypoint-initdb.d/
      - /etc/localtime:/etc/localtime
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
      - TZ=Asia/Shanghai
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306"